# Generated by Django 5.0.3 on 2024-03-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_guest_1', models.CharField(max_length=30, verbose_name='Имя первого гостя')),
                ('name_guest_2', models.CharField(max_length=30, verbose_name='Имя второго гостя')),
                ('drinks', models.CharField(max_length=30, verbose_name='Напитки')),
                ('presence_on_wedding', models.BooleanField(verbose_name='Присутствие на свадьбе')),
            ],
            options={
                'verbose_name': 'Свадьба',
                'ordering': ['name_guest_1'],
            },
        ),
    ]
