# Generated by Django 5.0.3 on 2024-03-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['name_guest_1'], 'verbose_name': 'Свадьба', 'verbose_name_plural': 'Свадьба'},
        ),
    ]
