# Generated by Django 5.0.3 on 2024-03-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_alter_guest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='name_slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
    ]
