# Generated by Django 5.0.3 on 2024-03-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_guest_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='one_plus',
            field=models.BooleanField(blank=True, default=False, verbose_name='+1 гость'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='drinks',
            field=models.CharField(blank=True, max_length=30, verbose_name='Напитки'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='presence_on_wedding',
            field=models.BooleanField(blank=True, verbose_name='Присутствие на свадьбе'),
        ),
    ]
