# Generated by Django 5.0.3 on 2024-03-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_guest_one_plus_alter_guest_drinks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['name_first_guest'], 'verbose_name': 'Свадьба', 'verbose_name_plural': 'Свадьба'},
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='name_guest_1',
            new_name='name_first_guest',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='name_guest_2',
            new_name='name_second_guest',
        ),
    ]
