# Generated by Django 5.0.3 on 2024-03-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0006_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='name_second_guest',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя второго гостя'),
        ),
    ]
