# Generated by Django 5.0.3 on 2024-03-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0008_alter_timer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='first_seconds_names',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имена+Фамилии'),
        ),
    ]
