# Generated by Django 5.0.3 on 2024-04-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0009_guest_first_seconds_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='drinks',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Напитки'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name_slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
    ]
